[build-system]
requires = [
  "setuptools>=64",
  "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "tglfnn_ukaea"
version = "0.2.0"
description = "Neural network surrogate of TGLF (weights only)"
readme = "README.md"
requires-python = ">=3.7"
license = "LGPL-3.0"
license-files = ["LICENSE"]
authors = [{name = "UKAEA"}]

# Only numpy is required for the tglfnn-ukaea weights only package
dependencies = ["numpy>2"]

[project.optional-dependencies]
dev = ["pandas","matplotlib"]

[project.urls]
Homepage = "https://github.com/ukaea/tglfnn-ukaea/"
Repository = "https://github.com/ukaea/tglfnn-ukaea/"

[tool.setuptools]
packages = ["tglfnn_ukaea"]

[tool.setuptools.package-data]
# Force the packager to include the pickled weights files
tglfnn_ukaea = ["weights/multimachine.pkl", "weights/step.pkl"]