D_over_chi: false
acquisition: random
acquisition_schedule: 30
asinh_scaling: false
batch_size: 512
candidate_size: 300000
classifier_type: ParallelEnsembleClassifier
commit_hash: d6a075ee53219568dd5846d5eb4b0fddc74072f5
common: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/ADEPT/adept/data/interim/TGLF/STEP-ramp-flat-top/common_STEP_ramp_flat_top.tglf
default_config: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/ADEPT/adept/configs/STEP_ramp_ftp_train.yaml
denormalise: false
dropout: 0.05
epochs: 200
flush: false
fluxes:
- pfe_gb
fluxes_from_cmd: pfe_gb
from_scratch: false
gkmodel: TGLF_STEP_ramp_ftop
hidden_size: 512
input_data_dir: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/ADEPT/adept/data/interim/TGLF/STEP-ramp-flat-top/
iterations: 1
labels_unavailable: false
learning_rate: 7.0e-05
loss: MSE
model_size: 6
num_cores: 76
num_estimators: 5
overwrite: true
patience: 10
processed_data_dir: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/ADEPT/adept/data/processed/TGLF/STEP-ramp-flat-top/SAT1/
project_name: STEP-ramp-ftop-2
regressor_type: ParallelEnsembleRegressor
resume_id: null
robust: false
run_sims: false
sample_size_debug: 1
save_dir: /rds/project/rds-aSo1XX0UOlw/ir-zani1/qualikiz/ADEPT/adept/outputs/quiet-mountain-45/
scaler_choice: StandardScaler
sim_data_dir: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/ADEPT/adept/data/raw/TGLF/STEP-ramp-flat-top/SAT1/
test_size: 5000000
theta_trapped_for_STs: true
top_keep: 512
train_size: 10000000
uncert_type: epistemic
use_all_outputs: true
use_classifier: false
use_classifier_for_acquisition: false
use_regressor: true
valid_size: 5000000
weight_decay: 0.0002
wrapper: TGLFWrapper
