batch_size: 512
commit_hash: edc54b0501d92d13d71e5e7584133d16dfbce4d3
common: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/ADEPT/adept/data/interim/TGLF/JET_hyper/SAT2/common_jet_hyper.tglf
default_config: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/ADEPT/adept/configs/JET_hyper_SAT2.yaml
dropout: 0.05
epochs: 250
flush: true
fluxes:
- efe_gb
- efi_gb
- pfi_gb
- pfe_gb
gkmodel: TGLF_multimachine_hyper
hidden_size: 512
input_data_dir: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/qualikiz/ADEPT/adept/data/interim/TGLF/JET_hyper/SAT2/
learning_rate: 0.0002
model_size: 6
num_estimators: 5
patience: 10
regressor_type: ParallelDeepEnsemble
test_size: 50000
theta_trapped_for_STs: false
train_size: 100000000
use_all_outputs: true
use_classifier: false
use_classifier_for_acquisition: false
use_regressor: true
valid_size: 10000
weight_decay: 0.0001
